FastFoodManagement/FastFoodManagement/Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaTaiKhoan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> ThoiGianTao { get; set; }
        public Nullable<int> LoaiTaiKhoan { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

FastFoodManagement/FastFoodManagement/Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FastFoodManagement.Models;
using PagedList;

namespace FastFoodManagement.Controllers
{
    public class TaiKhoansController : Controller
    {
        private FastFoodManagementEntities1 db = new FastFoodManagementEntities1();
        private Encrypt md5 = new Encrypt();

        // GET: TaiKhoans
        public ActionResult Index(int? page, string hoten, int? loaitaikhoan)
        {
            #region phan quyen
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Login");
            }
            TaiKhoan check = Session["TaiKhoan"] as TaiKhoan;
            if (check.LoaiTaiKhoan != 0)
            {
                //ViewBag.ThongBao = "Tài khoản của bạn không được phép truy cập!";
                if (check.LoaiTaiKhoan == 2)
                {
                    TempData["msg"] = "<script>alert('Tài khoản của bạn không được phép truy cập!');</script>";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["msg"] = "<script>alert('Chỉ admin mới được phép truy cập các bảng này!');</script>";
                    return RedirectToAction("Index", "Admin");
                }
            }
            #endregion

            #region tim kiem, phan trang
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if ((hoten == null || hoten == "") && loaitaikhoan == null)
                return View(db.TaiKhoans.ToList().OrderBy(n => n.LoaiTaiKhoan).ToPagedList(pageNumber, pageSize));
            else if ((hoten != null || hoten != "") && loaitaikhoan == null)
                return View(db.TaiKhoans.Where(n => n.KhachHang.TenKhachHang.Contains(hoten) || n.NhanVien.HoTen.Contains(hoten)).ToList().OrderBy(n => n.LoaiTaiKhoan).ToPagedList(pageNumber, pageSize));
            else if ((hoten == null || hoten == "") && loaitaikhoan != null)
                return View(db.TaiKhoans.Where(n => n.LoaiTaiKhoan == loaitaikhoan).ToList().OrderBy(n => n.LoaiTaiKhoan).ToPagedList(pageNumber, pageSize));
            else
                return View(db.TaiKhoans.Where(n => n.LoaiTaiKhoan == loaitaikhoan && (n.KhachHang.TenKhachHang.Contains(hoten) || n.NhanVien.HoTen.Contains(hoten))).ToList().OrderBy(n => n.LoaiTaiKhoan).ToPagedList(pageNumber, pageSize));
            #endregion
        }

        // GET: TaiKhoans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Create
        public ActionResult Create()
        {
            ViewBag.MaKhachHang = new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang");
            ViewBag.MaNhanVien = new SelectList(db.NhanViens, "MaNhanVien", "HoTen");
            return View();
        }

        // POST: TaiKhoans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTaiKhoan,MaKhachHang,MaNhanVien,TenTaiKhoan,MatKhau,ThoiGianTao,LoaiTaiKhoan,HinhAnh")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                taiKhoan.MatKhau = md5.Hash(taiKhoan.MatKhau);
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaKhachHang = new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang", taiKhoan.MaKhachHang);
            ViewBag.MaNhanVien = new SelectList(db.NhanViens, "MaNhanVien", "HoTen", taiKhoan.MaNhanVien);
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaKhachHang = new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang", taiKhoan.MaKhachHang);
            ViewBag.MaNhanVien = new SelectList(db.NhanViens, "MaNhanVien", "HoTen", taiKhoan.MaNhanVien);
            return View(taiKhoan);
        }

        // POST: TaiKhoans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTaiKhoan,MaKhachHang,MaNhanVien,TenTaiKhoan,MatKhau,ThoiGianTao,LoaiTaiKhoan,HinhAnh")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaKhachHang = new SelectList(db.KhachHangs, "MaKhachHang", "TenKhachHang", taiKhoan.MaKhachHang);
            ViewBag.MaNhanVien = new SelectList(db.NhanViens, "MaNhanVien", "HoTen", taiKhoan.MaNhanVien);
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
        //    if (taiKhoan == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(taiKhoan);
        //}

        //// POST: TaiKhoans/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FastFoodManagement/FastFoodManagement/Views/TaiKhoans/Create.cshtml
@model FastFoodManagement.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Tài khoản - thêm mới</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MaKhachHang, "Tên khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaKhachHang", null, "Tài khoản của nhân viên hoặc quản trị", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaNhanVien, "Tên nhân viên hoặc quản trị", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaNhanVien", null, "Tài khoản của khách hàng", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaNhanVien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenTaiKhoan, "Tên tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenTaiKhoan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhau, "Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ThoiGianTao, "Thời gian tạo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ThoiGianTao, new { htmlAttributes = new { @Value = DateTime.Now, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ThoiGianTao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LoaiTaiKhoan, "Loại tài khoản(0: Quản trị, 1: Nhân viên, 2: Khách hàng)", htmlAttributes: new { @class = "control-label col-md-10" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoaiTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoaiTaiKhoan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HinhAnh, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm mới" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/TaiKhoans/Delete.cshtml
@model FastFoodManagement.Models.TaiKhoan

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiTaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhachHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKhachHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.HoTen)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FastFoodManagement/FastFoodManagement/Views/TaiKhoans/Details.cshtml
@model FastFoodManagement.Models.TaiKhoan

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenTaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenTaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiTaiKhoan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiTaiKhoan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhachHang.TenKhachHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhachHang.TenKhachHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhanVien.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhanVien.HoTen)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaTaiKhoan }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FastFoodManagement/FastFoodManagement/Views/TaiKhoans/Edit.cshtml
@model FastFoodManagement.Models.TaiKhoan

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tài khoản - sửa thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaTaiKhoan)

        <div class="form-group">
            @Html.LabelFor(model => model.MaKhachHang, "Tên khách hàng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKhachHang", null, "Tài khoản của nhân viên hoặc quản trị", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhachHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNhanVien, "Tên nhân viên hoặc quản trị", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNhanVien", null, "Tài khoản của khách hàng", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNhanVien, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenTaiKhoan, "Tên tài khoản", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenTaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, "Mật khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThoiGianTao, "Thời gian tạo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThoiGianTao, new { htmlAttributes = new { @Value = DateTime.Now, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThoiGianTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoaiTaiKhoan, "Loại tài khoản(0: Quản trị, 1: Nhân viên, 2: Khách hàng)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoaiTaiKhoan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoaiTaiKhoan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/TaiKhoans/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FastFoodManagement.Models.TaiKhoan>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h4>Tài khoản</h4>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@using (Html.BeginForm("Index", "TaiKhoans", FormMethod.Get))
{
<div class="form-group form-inline">
    <input type="text" class="form-control" placeholder="Nhập họ tên:" name="hoten">
    <input type="text" class="form-control" placeholder="Nhập loại tài khoản:" name="loaitaikhoan">
    <button type="submit" class="btn btn-success">Tìm kiếm</button>
</div>
}
<table class="table table-striped">
    <tr>
        <th>
            Tên tài khoản
        </th>
        <th>
            Mật khẩu
        </th>
        <th>
            Thời gian tạo
        </th>
        <th>
            Loại tài khoản
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Tên khách hàng
        </th>
        <th>
            Tên nhân viên
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenTaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatKhau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThoiGianTao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiTaiKhoan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhachHang.TenKhachHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NhanVien.HoTen)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaTaiKhoan }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaTaiKhoan }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa mục này không?');" })
            </td>
        </tr>
    }

</table>

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang li {
        margin: 5px;
        font-size: 17px;
    }
</style>