FastFoodManagement/FastFoodManagement/Models/NhanVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public int MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public bool GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
    }
}

FastFoodManagement/FastFoodManagement/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FastFoodManagement.Models;
using PagedList;

namespace FastFoodManagement.Controllers
{
    public class NhanViensController : Controller
    {
        private FastFoodManagementEntities1 db = new FastFoodManagementEntities1();

        // GET: NhanViens
        public ActionResult Index(int? page, string hoten)
        {
            #region phan quyen
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Login");
            }
            TaiKhoan check = Session["TaiKhoan"] as TaiKhoan;
            if (check.LoaiTaiKhoan != 0)
            {
                //ViewBag.ThongBao = "Tài khoản của bạn không được phép truy cập!";
                if (check.LoaiTaiKhoan == 2)
                {
                    TempData["msg"] = "<script>alert('Tài khoản của bạn không được phép truy cập!');</script>";
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["msg"] = "<script>alert('Chỉ admin mới được phép truy cập các bảng này!');</script>";
                    return RedirectToAction("Index", "Admin");
                }
            }
            #endregion

            #region tim kiem, phan trang
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (hoten == null || hoten == "")
                return View(db.NhanViens.ToList().OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
            else
                return View(db.NhanViens.Where(n => n.HoTen.Contains(hoten)).ToList().OrderBy(n => n.HoTen).ToPagedList(pageNumber, pageSize));
            #endregion
        }

        // GET: NhanViens/Details/5
        public ActionResult Details()
        {
            TaiKhoan tk = Session["TaiKhoan"] as TaiKhoan;
            var taiKhoanNhanVien = db.TaiKhoans.Find(tk.MaTaiKhoan);
            ViewBag.TaiKhoan = taiKhoanNhanVien;
            NhanVien nhanVien = db.NhanViens.Find(tk.MaNhanVien);
            return View(nhanVien);
        }

        // GET: NhanViens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NhanViens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNhanVien,HoTen,GioiTinh,NgaySinh,SoDienThoai,DiaChi,Email")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhanVien);
        }

        // GET: NhanViens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanViens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNhanVien,HoTen,GioiTinh,NgaySinh,SoDienThoai,DiaChi,Email")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhanVien);
        }

        // GET: NhanViens/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    NhanVien nhanVien = db.NhanViens.Find(id);
        //    if (nhanVien == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(nhanVien);
        //}

        //// POST: NhanViens/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FastFoodManagement/FastFoodManagement/Views/NhanViens/Create.cshtml
@model FastFoodManagement.Models.NhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NhanVien</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.HoTen, "Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GioiTinh, "Giới tính(Tích: Nam)", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.GioiTinh)
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @Value = DateTime.Now, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai, "Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm mới" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/NhanViens/Delete.cshtml
@model FastFoodManagement.Models.NhanVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoDienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FastFoodManagement/FastFoodManagement/Views/NhanViens/Details.cshtml
@model FastFoodManagement.Models.NhanVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}
<h4>Thông tin tài khoản - quản trị</h4>

<table class="table table-striped">
    <tr>
        <th>Họ tên</th>
        <th>Giới tính</th>
        <th>Ngày sinh</th>
        <th>Số điện thoại</th>
        <th>Địa chỉ</th>
        <th>Email</th>
    </tr>
    <tr>
        <td>@Html.DisplayFor(model => model.HoTen)</td>
        <td>
            @if (Model.GioiTinh == true)
            {
                @:Nam
            }
            else
            {
                @:Nữ
            }
        </td>
        <td>@Html.DisplayFor(model => model.NgaySinh)</td>
        <td>@Html.DisplayFor(model => model.SoDienThoai)</td>
        <td>@Html.DisplayFor(model => model.DiaChi)</td>
        <td>@Html.DisplayFor(model => model.Email)</td>
    </tr>
</table>

<div class="form-horizontal" style="font-size: 17px;">
    <p>Tên tài khoản: @ViewBag.TaiKhoan.TenTaiKhoan</p>
    <p>Mật khẩu: @ViewBag.TaiKhoan.MatKhau</p>
    <p>
        Loại tài khoản:
        @if (ViewBag.TaiKhoan.LoaiTaiKhoan == 0)
        {
            @:Quản trị
        }
        @if (ViewBag.TaiKhoan.LoaiTaiKhoan == 1)
        {
            @:Nhân viên
        }
    </p>
</div>
<div>
    @Html.ActionLink("Trở về", "Index", "Admin")
</div>

FastFoodManagement/FastFoodManagement/Views/NhanViens/Edit.cshtml
@model FastFoodManagement.Models.NhanVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nhân viên - sửa dữ liệu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNhanVien)

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, "Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính(Tích: Nam)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDienThoai, "Số điện thoại" ,htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/NhanViens/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FastFoodManagement.Models.NhanVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h4>Nhân viên</h4>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@using (Html.BeginForm("Index", "NhanViens", FormMethod.Get))
{
    <div class="form-group form-inline">
        <input type="text" class="form-control" placeholder="Nhập họ tên:" name="hoten">
        <button type="submit" class="btn btn-success">Tìm kiếm</button>
    </div>
}
<table class="table table-striped">
    <tr>
        <th>
            Họ tên
        </th>
        <th>
            Giới tính
        </th>
        <th>
            Ngày sinh
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Địa chỉ
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.GioiTinh)*@
                @if (item.GioiTinh == true)
                {
                    @:Nam
                }
                else
                {
                    @:Nữ
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaNhanVien }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaNhanVien }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa mục này không?');" })
            </td>
        </tr>
    }

</table>

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang li {
        margin: 5px;
        font-size: 17px;
    }
</style>