FastFoodManagement/FastFoodManagement/Models/MonAn.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaMonAn { get; set; }
        public int MaChuDe { get; set; }
        public string TenMonAn { get; set; }
        public string DonGia { get; set; }
        public string HinhAnh { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}

FastFoodManagement/FastFoodManagement/Controllers/MonAnsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FastFoodManagement.Models;
using PagedList;

namespace FastFoodManagement.Controllers
{
    public class MonAnsController : Controller
    {
        private FastFoodManagementEntities1 db = new FastFoodManagementEntities1();

        // GET: MonAns
        public ActionResult Index(int? page, string tenmon, string gia)
        {
            #region phan quyen
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Login");
            }
            TaiKhoan check = Session["TaiKhoan"] as TaiKhoan;
            if (check.LoaiTaiKhoan != 0 && check.LoaiTaiKhoan != 1)
            {
                //ViewBag.ThongBao = "Tài khoản của bạn không được phép truy cập!";
                TempData["msg"] = "<script>alert('Tài khoản của bạn không được phép truy cập!');</script>";
                return RedirectToAction("Index", "Home");
            }
            #endregion

            #region tim kiem, phan trang
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if ((tenmon == null || tenmon == "") && (gia == null || gia == ""))
                return View(db.MonAns.ToList().OrderBy(n => n.TenMonAn).ToPagedList(pageNumber, pageSize));
            else if ((tenmon != null || tenmon != "") && (gia == null || gia == ""))
                return View(db.MonAns.SqlQuery("select * from MonAn where TenMonAn like '%'+@ten+'%'", new SqlParameter("@ten", tenmon)).ToList().OrderBy(n => n.TenMonAn).ToPagedList(pageNumber, pageSize));
            else if ((tenmon == null || tenmon == "") && (gia != null || gia != ""))
                return View(db.MonAns.SqlQuery("select * from MonAn where DonGia = @gia", new SqlParameter("@gia", gia)).ToList().OrderBy(n => n.TenMonAn).ToPagedList(pageNumber, pageSize));
            else
                return View(db.MonAns.SqlQuery("select * from MonAn where TenMonAn like '%'+@ten+'%' and DonGia = @gia", new SqlParameter("@ten", tenmon), new SqlParameter("@gia", gia)).ToList().OrderBy(n => n.TenMonAn).ToPagedList(pageNumber, pageSize));
            #endregion
        }

        // GET: MonAns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = db.MonAns.Find(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            List<MonAn> lstMonAn = db.MonAns.Where(n => n.MaChuDe == monAn.MaChuDe).OrderBy(n => n.TenMonAn).ToList();
            ViewBag.ListSame = lstMonAn;
            return View(monAn);
        }

        // GET: MonAns/Create
        public ActionResult Create()
        {
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe");
            return View();
        }

        // POST: MonAns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaMonAn,MaChuDe,TenMonAn,DonGia,HinhAnh,GhiChu")] MonAn monAn)
        {
            if (ModelState.IsValid)
            {
                db.MonAns.Add(monAn);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", monAn.MaChuDe);
            return View(monAn);
        }

        // GET: MonAns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MonAn monAn = db.MonAns.Find(id);
            if (monAn == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", monAn.MaChuDe);
            return View(monAn);
        }

        // POST: MonAns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaMonAn,MaChuDe,TenMonAn,DonGia,HinhAnh,GhiChu")] MonAn monAn)
        {
            if (ModelState.IsValid)
            {
                db.Entry(monAn).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", monAn.MaChuDe);
            return View(monAn);
        }

        //// GET: MonAns/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    MonAn monAn = db.MonAns.Find(id);
        //    if (monAn == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(monAn);
        //}

        // POST: MonAns/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            MonAn monAn = db.MonAns.Find(id);
            db.MonAns.Remove(monAn);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FastFoodManagement/FastFoodManagement/Views/MonAns/Create.cshtml
@model FastFoodManagement.Models.MonAn

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Món ăn - thêm mới</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.MaMonAn, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaMonAn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaMonAn, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, "Tên chủ đề", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenMonAn, "Tên món ăn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMonAn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMonAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, "Đơn giá (VNĐ)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/MonAns/Delete.cshtml
@model FastFoodManagement.Models.MonAn

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonAn</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenMonAn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenMonAn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FastFoodManagement/FastFoodManagement/Views/MonAns/Details.cshtml
@model FastFoodManagement.Models.MonAn
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/HomeLayout.cshtml";
}

@*<main role="main" class="probootstrap-main js-probootstrap-main">*@
@Html.ActionLink("Trở về", "Index", "Home")
<div class="container-fluid">
    <div class="row mt-0">
        <div class="col-xl-8 col-lg-12" style="display:inline;">
            <div class="mb-5" style="float:left;  padding-top: 20px;"><img src="@Url.Content("~/HinhAnh/"+@Model.HinhAnh)" alt="Card image cap" style="width:500px; height:500px; position: center;"></div>

            <div class="row justify-content-center">
                <div class="col-xl-8 col-lg-12 " style="float:left; width: 700px;">
                    <h1 class="mb-5">@Model.TenMonAn</h1>
                    <p>@Model.GhiChu</p>
                </div>
            </div>
        </div>
    </div>

    <div class="tag" style="padding-top: 10px;">Giá tiền: @String.Format("{0:0,0}", @Model.DonGia) VNĐ</div>
    @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMaMonAn = @Model.MaMonAn, @strURL = Request.Url.ToString() }))
    {
        <input type="submit" style="cursor:pointer" value="Thêm vào giỏ hàng " id="btnGioHang" class="btn btn-success">
    }
    <!-- END row -->

    <section class="probootstrap-section">
        <div class="container-fluid">
            <div class="row mb-5 justify-content-center">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-8 mx-auto">
                            <p class="h1 mb-5 mt-0">Các món tương tư</p>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="owl-carousel probootstrap-owl">
                        @foreach (var item in @ViewBag.ListSame)
                        {
                            <div class="item">
                                <img src="@Url.Content("~/HinhAnh/" + item.HinhAnh)" class="img-fluid" alt="">
                                <div class="p-4 border border-top-0">
                                    <h4>@item.TenMonAn</h4>
                                    <p>@item.GhiChu</p>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>



        </div>
    </section>
</div>

FastFoodManagement/FastFoodManagement/Views/MonAns/Edit.cshtml
@model FastFoodManagement.Models.MonAn

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Món ăn - sửa thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaMonAn)

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, "Tên chủ đề", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaChuDe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenMonAn, "Tên món ăn" , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenMonAn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenMonAn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonGia, "Đơn giá (VNĐ)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/MonAns/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FastFoodManagement.Models.MonAn>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h4>Món ăn</h4>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@using (Html.BeginForm("Index", "MonAns", FormMethod.Get))
{
<div class="form-group form-inline">
    <input type="text" class="form-control" placeholder="Nhập tên món ăn:" name="tenmon">
    <input type="text" class="form-control" placeholder="Nhập giá:" name="gia">
    <button type="submit" class="btn btn-success">Tìm kiếm</button>
</div>
}
<table class="table table-striped">
    <tr>
        <th>
            Tên món ăn
        </th>
        <th>
            Đơn giá (VNĐ)
        </th>
        <th>
            Hình ảnh
        </th>
        <th>
            Ghi chú
        </th>
        <th>
            Tên chủ đề
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenMonAn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HinhAnh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChuDe.TenChuDe)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaMonAn }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaMonAn }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa mục này không?');" })
            </td>
        </tr>
    }
</table>

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang li {
        margin: 5px;
        font-size: 17px;
    }
</style>