FastFoodManagement/FastFoodManagement/Models/GiamGia.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public int MaKhuyenMai { get; set; }
        public int MaHoaDon { get; set; }
        public bool ApDung { get; set; }
    
        public virtual HoaDonThanhToan HoaDonThanhToan { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}

FastFoodManagement/FastFoodManagement/Controllers/GiamGiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FastFoodManagement.Models;
using PagedList;

namespace FastFoodManagement.Controllers
{
    public class GiamGiasController : Controller
    {
        private FastFoodManagementEntities1 db = new FastFoodManagementEntities1();

        // GET: GiamGias
        public ActionResult Index(int? page, string ghichu, string mota)
        {
            #region phan quyen
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "Login");
            }
            TaiKhoan check = Session["TaiKhoan"] as TaiKhoan;
            if (check.LoaiTaiKhoan != 0 && check.LoaiTaiKhoan != 1)
            {
                //ViewBag.ThongBao = "Tài khoản của bạn không được phép truy cập!";
                TempData["msg"] = "<script>alert('Tài khoản của bạn không được phép truy cập!');</script>";
                return RedirectToAction("Index", "Home");
            }
            #endregion

            #region tim kiem, phan trang
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if ((ghichu == null || ghichu == "") && (mota == null || mota == ""))
                return View(db.GiamGias.ToList().OrderBy(n => n.MaKhuyenMai).ToPagedList(pageNumber, pageSize));
            else if ((ghichu != null || ghichu != "") && (mota == null || mota == ""))
                return View(db.GiamGias.Where(n => n.HoaDonThanhToan.GhiChu.Equals(ghichu)).ToList().ToPagedList(pageNumber, pageSize));
            else if ((ghichu == null || ghichu == "") && (mota != null || mota != ""))
                return View(db.GiamGias.Where(n => n.KhuyenMai.MoTa.Contains(mota)).ToList().ToPagedList(pageNumber, pageSize));
            else
                return View(db.GiamGias.Where(n => n.KhuyenMai.MoTa.Contains(mota) && n.HoaDonThanhToan.GhiChu.Equals(ghichu)).ToList().OrderBy(n => n.MaKhuyenMai).ToPagedList(pageNumber, pageSize));
            #endregion
        }

        // GET: GiamGias/Create
        public ActionResult Create()
        {
            ViewBag.MaHoaDon = new SelectList(db.HoaDonThanhToans, "MaHoaDon", "GhiChu");
            ViewBag.MaKhuyenMai = new SelectList(db.KhuyenMais, "MaKhuyenMai", "MoTa");
            return View();
        }

        // POST: GiamGias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKhuyenMai,MaHoaDon,ApDung")] GiamGia giamGia)
        {
            if (ModelState.IsValid)
            {
                db.GiamGias.Add(giamGia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaHoaDon = new SelectList(db.HoaDonThanhToans, "MaHoaDon", "GhiChu", giamGia.MaHoaDon);
            ViewBag.MaKhuyenMai = new SelectList(db.KhuyenMais, "MaKhuyenMai", "MoTa", giamGia.MaKhuyenMai);
            return View(giamGia);
        }

        // GET: GiamGias/Edit/5
        public ActionResult Edit(int? mahoadon, int? makhuyenmai)
        {
            if (mahoadon == null && makhuyenmai == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiamGia giamGia = db.GiamGias.SingleOrDefault(n => n.MaHoaDon == mahoadon && n.MaKhuyenMai == makhuyenmai);
            if (giamGia == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaHoaDon = new SelectList(db.HoaDonThanhToans, "MaHoaDon", "GhiChu", giamGia.MaHoaDon);
            ViewBag.MaKhuyenMai = new SelectList(db.KhuyenMais, "MaKhuyenMai", "MoTa", giamGia.MaKhuyenMai);
            return View(giamGia);
        }

        // POST: GiamGias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKhuyenMai,MaHoaDon,ApDung")] GiamGia giamGia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(giamGia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaHoaDon = new SelectList(db.HoaDonThanhToans, "MaHoaDon", "GhiChu", giamGia.MaHoaDon);
            ViewBag.MaKhuyenMai = new SelectList(db.KhuyenMais, "MaKhuyenMai", "MoTa", giamGia.MaKhuyenMai);
            return View(giamGia);
        }

        public ActionResult Delete(int mahoadon, int makhuyenmai)
        {
            GiamGia giamGia = db.GiamGias.SingleOrDefault(n => n.MaHoaDon == mahoadon && n.MaKhuyenMai == makhuyenmai);
            db.GiamGias.Remove(giamGia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FastFoodManagement/FastFoodManagement/Views/GiamGias/Create.cshtml
@model FastFoodManagement.Models.GiamGia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Giảm giá - thêm mới</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaKhuyenMai, "Tên khuyến mãi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaKhuyenMai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaKhuyenMai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaHoaDon, "Mã hóa đơn", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaHoaDon", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaHoaDon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApDung, "Áp dụng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ApDung)
                    @Html.ValidationMessageFor(model => model.ApDung, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/GiamGias/Delete.cshtml
@model FastFoodManagement.Models.GiamGia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GiamGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoaDonThanhToan.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoaDonThanhToan.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuyenMai.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuyenMai.MoTa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FastFoodManagement/FastFoodManagement/Views/GiamGias/Details.cshtml
@model FastFoodManagement.Models.GiamGia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>GiamGia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoaDonThanhToan.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoaDonThanhToan.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KhuyenMai.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KhuyenMai.MoTa)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FastFoodManagement/FastFoodManagement/Views/GiamGias/Edit.cshtml
@model FastFoodManagement.Models.GiamGia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Giám giả - sửa thông tin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKhuyenMai)

        @Html.HiddenFor(model => model.MaHoaDon)

        <div class="form-group">
            @Html.LabelFor(model => model.ApDung, "Áp dụng",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ApDung)
                    @Html.ValidationMessageFor(model => model.ApDung, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

FastFoodManagement/FastFoodManagement/Views/GiamGias/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<FastFoodManagement.Models.GiamGia>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/Admin1Layout.cshtml";
}

<h4>Giảm giá</h4>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@using (Html.BeginForm("Index", "GiamGias", FormMethod.Get))
{
    <div class="form-group form-inline">
        <input type="text" class="form-control" placeholder="Nhập ghi chú - hóa đơn thanh toán:" name="ghichu">
        <input type="text" class="form-control" placeholder="Nhập mô tả - khuyến mãi:" name="mota">
        <button type="submit" class="btn btn-success">Tìm kiếm</button>
    </div>
}
<table class="table table-striped">
    <tr>
        <th>
            Áp dụng
        </th>
        <th>
            Ghi chú - Hóa đơn thanh toán
        </th>
        <th>
            Mô tả
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApDung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoaDonThanhToan.GhiChu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KhuyenMai.MoTa)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { mahoadon = item.MaHoaDon, makhuyenmai = item.MaKhuyenMai }) |
                @Html.ActionLink("Xóa", "Delete", new { mahoadon = item.MaHoaDon, makhuyenmai = item.MaKhuyenMai }, new { onclick = "return confirm('Bạn có chắc chắn muốn xóa mục này không?');" })
            </td>
        </tr>
    }

</table>

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang li {
        margin: 5px;
        font-size: 17px;
    }
</style>